camera:
  resolution:
    width: ${CAMERA_RESOLUTION_WIDTH:-640}
    height: ${CAMERA_RESOLUTION_HEIGHT:-480}
  framerate: ${CAMERA_FRAMERATE:-10}
trigger:
  cls: ${TRIGGER_CLS:-DistanceSensorTrigger}
  parameters:
    echo: ${TRIGGER_PARAMETERS_ECHO:-20}
    trigger: ${TRIGGER_PARAMETERS_TRIGGER:-26}
    distance_min: ${TRIGGER_PARAMETERS_DISTANCE_MIN:-45}
    distance_max: ${TRIGGER_PARAMETERS_DISTANCE_MAX:-65}
    led: ${TRIGGER_PARAMETERS_LED:-24}
  delay: ${TRIGGER_DELAY:-3}
leds:
  green: ${LEDS_GREEN_PIN:-27}
  red: ${LEDS_RED_PIN:-14}
  yellow: ${LEDS_YELLOW_PIN:-23}
  blue: ${LEDS_BLUE_PIN:-22}
